### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [is541-sibsutis/quiz#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:

1. В [wiki](https://github.com/is541-sibsutis/quiz/wiki) проекта написана статья с ТЗ.
1. В [issues](https://github.com/is541-sibsutis/quiz/issues) созданы задачи.
1. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by GreyWolfWild** [comment]
Т3 составили. Что надо исправить?

**Comment by evgeny-p** [comment]
Не описаны форматы файлов: в каком формате хранятся вопросы, в каком формате сохраняются результаты. К моменту реализации это должно быть описано.

Оформите план работ как задачи. Задача перед началом работы над ней назначается на исполнителя (поле Assignee).

Можно приступать к выполнению, уточняя ТЗ по мере необходимости.
